### ISSUE TITLE
Working against gollum wiki

### ISSUE THREAD

**Issue by hangvar** [hybridgroup/gitnesse#22]
Hi,

I've tried to setup gitnesse against a "locally" installed gollum wiki, but I get this error when trying to do "gitnesse push":

 Creating local copy of remote wiki.
/home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/git-1.2.6/lib/git/lib.rb:718:in `command': git clone "--" "http://localhost:4567" "/home/nrkhan/.gitnesse/svn"  2>&1:Initialized empty Git repository in /home/nrkhan/.gitnesse/svn/.git/ (Git::GitExecuteError)
error:  while accessing http://localhost:4567/info/refs

fatal: HTTP request failed
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/git-1.2.6/lib/git/lib.rb:69:in `clone'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/git-1.2.6/lib/git/base.rb:55:in`clone'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/git-1.2.6/lib/git.rb:88:in `clone'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/wiki.rb:127:in`clone'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/wiki.rb:114:in `clone_or_update'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/wiki.rb:23:in`initialize'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/cli/helpers/wiki_helpers.rb:16:in `new'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/cli/helpers/wiki_helpers.rb:16:in`clone_wiki'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/cli/task/push.rb:20:in `perform'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/lib/gitnesse/cli.rb:23:in`parse'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/gems/gitnesse-1.0.0/bin/gitnesse:5:in `<top (required)>'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/bin/gitnesse:23:in`load'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/bin/gitnesse:23:in `<main>'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in`eval'
        from /home/nrkhan/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'

**Comment by stewart** [comment]
Are you following the ["Running" section of the Gollum readme](https://github.com/gollum/gollum#running)? I don't believe the web server actually provides Git access to the backing wiki, so I don't think this would work. You'd need to give Gitnesse the filesystem path to the Gollum wiki you want to use.
